version: '3.1'

services:

  mongo:
    container_name: mongoDB
    image: mongo
    restart: always
    volumes:
      - ./src/kerok-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
    - 27017:27017